title: scratch-cat-goes-skiing-quiz
hero_image: images/banner.png
description: scratch-cat-goes-skiing-quiz description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-08"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
